name: BlueMapFloodgate
version: ${project.version}
main: com.technicjelle.bluemapfloodgate.Main
api-version: 1.17
folia-supported: true
depend:
  - BlueMap
  - floodgate
author: TechnicJelle
description: ${project.description}
website: ${project.url}
