name: BlueMapFloodgate
version: ${project.version}
main: com.technicjelle.bluemapfloodgate.BlueMapFloodgate
api-version: 1.17
depend:
  - BlueMap
  - floodgate
author: TechnicJelle
description: ${project.description}
website: ${project.url}
